# Generated by Django 3.0.4 on 2020-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20200407_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=30, verbose_name='La direccion'),
        ),
    ]
