# Generated by Django 3.0.4 on 2020-05-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_auto_20200414_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
